HAND_DATO EQU 40H
HAND_ESTADO EQU 41H
ORG 1000H
    MSG DB "INGENIERIA E INFORMATICA"
    FIN DB ?
ORG 2000H
    IN AL, HAND_ESTADO
    AND AL, 07FH ; ponemos bit 7 en 0 para usar metodo polling
    OUT HAND_ESTADO, AL

    MOV BX, OFFSET MSG
POLL: IN AL, HAND_ESTADO
    AND AL, 1
    JNZ POLL

    MOV AL, [BX]
    OUT HAND_DATO, AL

    INC BX
    CMP BX, OFFSET FIN
    JNZ POLL
    INT 0
END
