PA EQU 30H
CA EQU 32H
ORG 1000H
	PREND_MSG DB "Llave prendida"
	APAG_MSG DB "Llave apagada"
	FIN_DIR DB ?
ORG 2000H
	MOV AL, 80H
	OUT CA, AL
	MOV AL, 00H
	OUT PA, AL ; Se "limpia" lo que había antes en PA
	NOP ; Hacer cambios a las llaves
	IN AL, PA
	CMP AL, 0
	JNZ ELSE
	MOV BX, OFFSET APAG_MSG
	MOV AL, OFFSET FIN_DIR - OFFSET APAG_MSG
	JMP FIN_IF
ELSE: MOV BX, OFFSET PREND_MSG
	MOV AL, OFFSET APAG_MSG - OFFSET PREND_MSG
FIN_IF: INT 7
	HLT
END
