N EQU 5
PIC EQU 20H
HAND_DATO EQU 40H
HAND_ESTADO EQU 41H
ORG 48
	DIR_HS DW RUT_HS
ORG 1000H
	INPUT DB ?
ORG 3000H
RUT_HS: PUSH AX
	MOV AL, [BX]
	OUT HAND_DATO, AL
	CMP CH, 0 ; preguntar sentido
	JNZ ELSE
	INC BX
	JMP FIN_IF
ELSE: DEC BX
FIN_IF: DEC CL
	JNZ FIN_RUT
	CMP CH, 1
	JNZ ELSE2
	INT 0
ELSE2: INC CH ; cambia sentido
	MOV CL, N
	MOV BX, OFFSET INPUT + N - 1
FIN_RUT: MOV AL, 20H
	OUT PIC, AL
	POP AX
	IRET
ORG 2000H
	MOV CL, N
	MOV BX, OFFSET INPUT
LECTURA: INT 6
	INC BX
	DEC CL
	JNZ LECTURA
	CLI
	MOV AL, 0FFH
	OUT HAND_ESTADO, AL
	MOV AL, 11111011B ; enmascarar interrupciones
	OUT PIC+1, AL
	MOV AL, 12 ; id 12 a int 2
	OUT PIC+6, AL
	MOV CH, 0 ; booleano para identificar sentido de impresion
	MOV CL, N ; contador de iteraciones
	MOV BX, OFFSET INPUT
	STI
LOOP: JMP LOOP
	INT 0
END
