ORG 3000H
LONGITUD: MOV DX, 0
	MOV BX, AX
LOOP_LONG: CMP BYTE PTR [BX], 00H
	JZ FIN_LOOP_LONG
	INC DX
	INC BX
	JMP LOOP_LONG
FIN_LOOP_LONG: RET
ORG 1000H
	STRING DB "HOLA MUNDO"
	FIN DB 00H
ORG 2000H
	MOV BX, OFFSET STRING
	CALL LONGITUD
END
