ORG 3000H
CONTAR_MIN: PUSH BX ; IN BX, OUT DX
	PUSH CX
	MOV DX, 0
LOOP1: MOV CH, 0
	MOV CL, [BX]
	CMP CX, 0 ; SE LLEGO A FINAL
	JZ FIN_CONTAR_MIN
	PUSH CX ; PARAMETRO
	CALL ES_MIN
	POP CX ; SALIDA
	CMP CX, 0 ; == FALSE
	JZ NO_ES
	INC DX
NO_ES: INC BX
	JMP LOOP1
FIN_CONTAR_MIN: POP CX
	POP BX
	RET
	
ES_MIN: PUSH BX
	MOV BX, SP
	PUSH AX
	PUSH CX
	ADD BX, 4
	MOV AX, [BX]
	MOV CX, 61H ; = 'a'
LOOP2: CMP CX, 7BH
	JZ FALSO
	CMP AX, CX
	JZ VERDAD
	INC CX
	JMP LOOP2
FALSO: MOV WORD PTR [BX], 0
	JMP FIN_ES_MIN
VERDAD: MOV WORD PTR [BX], 1
FIN_ES_MIN: POP CX
	POP AX
	POP BX
	RET
ORG 1000H
	STRING DB "hOLa7"
	FIN_STR DB 00H
ORG 2000H
	MOV BX, OFFSET STRING
	CALL CONTAR_MIN
	HLT
END