ORG 3000H
MUL_A: MOV DX, 0  ; AX y CX valores de operandos. DX valor de retorno
	CMP CX, 0
	JZ FIN_A
FOR_A: ADD DX, AX
	DEC CX
	JNZ FOR_A
FIN_A: RET

MUL_B: MOV DX, 0  ; AX y CX referencias a operandos. DX valor de retorno
	MOV BX, AX
	CMP WORD PTR [BX], 0
	JZ FIN_B
FOR_B: MOV BX, CX
	ADD DX, [BX]
	MOV BX, AX
	DEC WORD PTR [BX]
	JNZ FOR_B
FIN_B: RET

ORG 1000H
	NUM1 DW 4
	NUM2 DW 3
	RES DW ?
ORG 2000H
	MOV DX, 0
FOR: CMP NUM2, 0
	JZ FIN_FOR
	ADD DX, NUM1
	DEC NUM2
	JMP FOR
FIN_FOR: MOV NUM2, 3
	MOV AX, NUM1
	MOV CX, NUM2
	CALL MUL_A
	
	MOV AX, OFFSET NUM1
	MOV CX, OFFSET NUM2
	CALL MUL_B
	HLT
END
