ORG 1000h
	TABLA DB 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
	FIN   DB ?
	TOTAL DB ?
	MAX   DB 13
ORG 2000h
	MOV AH, MAX
	MOV AL, 0
	MOV CL, OFFSET FIN - OFFSET TABLA
	MOV BX, OFFSET TABLA
LOOP: CMP AH, [BX] ; MAX > N
	JC FIN_IF
	INC AL
FIN_IF: INC BX
	DEC CL
	JNZ LOOP
	MOV TOTAL, AL
	HLT
END
