ORG 1000h
	DIR DW 3675h ; DIRECCION DE TABLA
	MAX DB 16
ORG 2000h
	MOV CL, 0 ; ACUMULADOR DE MULTIPLOS
	MOV AL, MAX ; MAX
	MOV BX, DIR ; CONTADOR DE DIRECCIONES
SUMAR: ADD CL, 5
	CMP AL, CL
	JC FIN_LOOP
	MOV [BX], CL
	INC BX
	JMP SUMAR
FIN_LOOP: HLT
END
