ORG 1000H
	FAIL_MSG DB "ERROR: NO ES UN DIGITO"
	MAS DB " + "
	IGUAL DB " = "
	NUM1 DB ?
	NUM2 DB ?
ORG 3000H
ES_NUM: CMP AL, 30H ; AL parametro del numero en forma de caracter
	JS FIN_ES_NUM
	CMP AL, 3AH
	JNS FIN_ES_NUM
	MOV AL, 0
FIN_ES_NUM: RET
CONVER_DEC: SUB AL, 30H ; AL parametro del caracter a convertir
	RET
CONVER_CHAR: ADD AL, 30H ; AL parametro del numero a convertir
	RET
ORG 2000H
	MOV BX, OFFSET NUM1
	INT 6
	MOV AL, NUM1
	CALL ES_NUM
	CMP AL, 0
	JNZ FAIL
	MOV AL, 1
	INT 7

	MOV BX, OFFSET MAS
	MOV AL, 3
	INT 7
	
	MOV BX, OFFSET NUM2
	INT 6
	MOV AL, NUM2
	CALL ES_NUM
	CMP AL, 0
	JNZ FAIL
	MOV AL, 1
	INT 7
	
	MOV BX, OFFSET IGUAL
	MOV AL, 3
	INT 7

	MOV AL, NUM1
	CALL CONVER_DEC
	MOV DL, AL
	MOV AL, NUM2
	CALL CONVER_DEC
	ADD DL, AL
	MOV BX, OFFSET NUM1

	CMP DL, 10
	JS UN_DIG
	MOV NUM1, 31H
	MOV AL, 1
	INT 7
	SUB DL, 10
UN_DIG: MOV AL, DL
	CALL CONVER_CHAR
	MOV NUM1, AL
	MOV AL, 1
	INT 7
	JMP FIN
FAIL: MOV BX, OFFSET FAIL_MSG
	MOV AL, OFFSET MAS - OFFSET FAIL_MSG
	INT 7
FIN: HLT
END
